### ISSUE TITLE
entity_bulk drops classificationNames

### ISSUE THREAD

**Issue by mgorsk1** [verdan/pyatlasclient#10]
I have setup dev Atlas instance with ~20 table entities. Every entity has attached single classification. When using basic_search every entity contains correct `classificationNames` attribute (single entry list). When using subsequent entity_bulk `classificationNames` is empty (for the same entity).

```
results = self.driver.search_basic(**full_params)

search_chunk = extract_entities(results)
print(search_chunk[0].classificationNames)  # every entry in search_chunk has classificationNames filled out

if relationships:
    guids = [table.guid for table in search_chunk]

    if guids:
        bulk_collection = self.driver.entity_bulk(guid=guids, ignoreRelationships=False)

        for collection in bulk_collection:
            search_chunk = list(collection.entities())
            classifiations = search_chunk[0].classificationNames

            if classifiations:
                print(classifiations)
            else:
                print('classifications empty')
```

below results of print statements

```
['storage_node']
classifications empty
```

**Comment by verdan** [comment]
This is because both the endpoints have different response model and structure. 
Basic Search returns: http://atlas.apache.org/api/v2/json_AtlasSearchResult.html (basically most of the header information)
Entity Bulk returns: http://atlas.apache.org/api/v2/json_AtlasEntitiesWithExtInfo.html (every possible detail of entities)

Nothing we can fix in this client.
